[Tests update] Added tests compatibility for surface mode. Minor bugs fixed.

diff --git a/tests/2exec/comp2exec b/tests/2exec/comp2exec
--- a/tests/2exec/comp2exec
+++ b/tests/2exec/comp2exec
@@ -24,7 +24,7 @@
 # first line is exclusive flags (use at most one together with manual definitions below)
 FLAGS="SPA_EXT SPA_STAN SURF_EXT SURF_STAN RD_EXT RD_STAN RD_TRICKY"
 # second - independent flags and internal variables
-EXTRAS="$FLAGS FFTCOMP GUIDIFF REFPATH ADDASEQ ADDAMPI ADDAOCL ADDASPASEQ ADDASPAMPI ADDASPAOCL OLDIGNORE"
+EXTRAS="$FLAGS FFTCOMP GUIDIFF REFPATH ADDASEQ ADDAMPI ADDAOCL ADDASPASEQ ADDASPAMPI ADDASPAOCL OLDIGNORE SURF_RE SURF_IM"
 
 # ----- exclusive flags START -----
 # In the following the exclusive flags are described. You can uncomment them or define from the command line (see 
@@ -60,13 +60,13 @@ EXTRAS="$FLAGS FFTCOMP GUIDIFF REFPATH ADDASEQ ADDAMPI ADDAOCL ADDASPASEQ ADDASP
 # Also useful for comparison of sparse version with the standard one (set automatically in that case)
 #FFTCOMP=1
 
-# Using a GUI diff program allows quick estimate of the importance of differences (e.g. when there are differences in 
+# Using a GUI diff program allows quick estimate of the importance of differences (e.g. when there are differences in
 # minor digits of many numbers). However, most effort should be put in improving mycmp below, so that only significant 
 # errors remain. 
 # GUIDIFF is a flag enabling use of GUI diff. If it is set to 'strip', stripped files are used for comparison. If used,
 # the existing program must be specified by GUIDIFFPROG. Options include, for example: tortoisemerge, meld, vimdiff
 #GUIDIFF=strip
-GUIDIFFPROG=tortoisemerge
+GUIDIFFPROG=Meld.exe
 
 # Look below for "!!!", which mark the places where adjustments are probably need to be done
 
@@ -78,7 +78,7 @@ echo "----------------------------------------"
 # Location of sample input files (not needed if all input files are already present)
 INPUTDIR="./../../input"
 # Location of binaries
-ADDASEQ="./../../src/seq/adda"
+ADDASEQ="./../../src/seq/adda.exe"
 ADDASPASEQ="./../../src/seq/adda_spa"
 ADDAMPI="./../../src/mpi/adda_mpi"
 ADDASPAMPI="./../../src/mpi/adda_spa_mpi"
@@ -93,7 +93,7 @@ OLDIGNORE="$OLDIGNORE|^ADDA v\.|^Built with GNU compilers|^      using MinGW-64|
 OLDIGNORE="$OLDIGNORE|^(GPU-accelerated|Parallel) version conforming|^Particle is placed"
 
 # Path to reference binaries, examples: "." or "./../../win64"
-REFPATH=./../../win64
+REFPATH=./../../win64 # ./../../../ADDA/ADDA/src/seq
 # MPI command prefix
 MPIRUN="mpiexec -n 4"
 # Choice of gpu (OpenCL device), if more than one
@@ -143,14 +143,18 @@ else
   SEQTEST="$ADDASEQ"
   MPITEST="$ADDAMPI"
   OCLTEST="$ADDAOCL"
-  SEQREF="$REFPATH/adda" # !!! This may be adjusted
+  SEQREF="$REFPATH/adda.exe" # !!! This may be adjusted
   MPIREF="$REFPATH/adda_mpi" # !!! This may be adjusted
   OCLREF="$REFPATH/adda_ocl" # !!! This may be adjusted
 fi
 # Other flags modify suffixes
 if [ -n "$SURF_EXT" ]; then
   DEFSUITE=suite_surf
-  SUFREF="-surf 4 2 0.1"
+  if [ -n "$SURF_RE" ]; then
+    SUFREF="-surf 4 $SURF_RE $SURF_IM -prop 0 0 -1"
+  else
+    SUFREF="-surf 4 2 0.1"
+  fi
   SUFTEST="$SUFREF"
 fi
 if [ -n "$SURF_STAN" ]; then
@@ -210,11 +214,11 @@ function assign_test {
 }
 
 set_default MODE "$1" seq
-if [ $MODE == "seq" ]; then
+if [ "$MODE" == "seq" ]; then
   assign_test EXECREF "$REF_EQ_TEST" "$SEQTEST" "$SEQREF"
   EXECREF="$EXECREF $SUFREF"
   EXECTEST="$SEQTEST $SUFTEST"
-elif [ $MODE == "mpi" ]; then
+elif [ "$MODE" == "mpi" ]; then
   assign_test EXECREF "$REF_EQ_TEST" "$MPITEST" "$MPIREF"
   EXECREF="$MPIRUN $EXECREF $SUFREF"
   EXECTEST="$MPIRUN $MPITEST $SUFTEST"
@@ -300,6 +304,15 @@ function numigndiff {
   cleanfile $2 $TMPTEST "$3" "$4"
   diff $TMPREF $TMPTEST | $AWK -f diff_numeric.awk -v abs_tol=1e-$atol -v rel_tol=1e-$rtol -  >&2
 }
+
+calc_norm(){
+    tail -n +2 "$1" | cut -d " " -f 2- | tr -s ' '  '\n' > temp1
+    tail -n +2 "$2" | cut -d " " -f 2- | tr -s ' '  '\n' > temp2
+    paste temp1 temp2 | awk '{s += $1 > $2 ? $1 - $2 : $2 - $1}; {d += $1 > 0 ? $1 : -$1}; END{print d!=0 ? s/d : inf, s/NR}'
+    rm temp1
+    rm temp2
+}
+
 function igndiff {
   # Performs comparison of two files, ignoring differences in lines matching regexp $3 and all the differences after the
   # line matching regexp $4.
@@ -310,7 +323,7 @@ function igndiff {
 function asmin {
   # Assign variable named $1 to $2 if its current value is larger
   if [[ -z ${!1} || ${!1} -gt $2 ]]; then
-    eval $1=$2
+    eval "$1"="$2"
   fi
 }
 function mycmp {
@@ -337,6 +350,10 @@ function mycmp {
     asmin atol 5
     asmin rtol 2
   fi
+  if [ -n "$SURF_EXT" ]; then
+    asmin atol 14
+    asmin rtol 2
+  fi
   # behavior is mainly determined by file name
   base=`basename $1`
   IGNORE=""
@@ -344,6 +361,9 @@ function mycmp {
     append IGNORE "$OLDIGNORE"
   fi
   if [ "$base" == $SONAME ]; then
+    if [ -n "$SURF_EXT" ]; then
+      return 0
+    fi
     append IGNORE "^all data is saved in '.*'|No real dipoles are assigned"
     if [[ -n "$RD_STAN" || -n "$RD_TRICKY" ]]; then
       append IGNORE "^Using rectangular dipoles|^lambda:|^CoupleConstant:"
@@ -381,6 +401,9 @@ function mycmp {
     asmin rtol 4
     numigndiff $1 $2 "$IGNORE" "$CUT"
   elif [ "$base" == $SOREF ]; then
+    if [ -n "$SURF_EXT" ]; then
+      return 0
+    fi
     if [[ $MODE == "mpi" || $MODE == "mpi_seq" ]]; then
       CUT="^Error posting writev, " # due to typical random errors of MPICH under Windows
     else
@@ -389,6 +412,9 @@ function mycmp {
     append IGNORE "^Usage: '.*'|^Type '.*' for details"
     igndiff $1 $2 "$IGNORE" "$CUT"
   elif [ "$base" == "log" ]; then
+    if [ -n "$SURF_EXT" ]; then
+      return 0
+    fi
     append IGNORE "^Generated by ADDA v\.|^command: '.*'|^Symmetr|^No symmetries"
     if [[ -n "$RD_STAN" || -n "$RD_TRICKY" ]]; then
       append IGNORE "^Using rectangular dipoles|^Dipoles/lambda:|^CoupleConstant:"
@@ -427,16 +453,30 @@ function mycmp {
     if [ -n "$RD_TRICKY" ]; then
       asmin atol 1
       asmin rtol 1
+    elif [ -n "$SURF_EXT" ]; then
+      asmin atol 14
+      asmin rtol 2
     else
-      asmin atol 8
+      asmin atol 14
       asmin rtol 5
     fi
-    numdiff $1 $2
+    read rel_error abs_error <<< "$(calc_norm "$1" "$2")"
+    if (( $(echo "$abs_error 1e-$atol" | awk 'END{print ($1 > $2)}') && $(echo "$rel_error 1e-$rtol" | awk 'END{print ($1 > $2)}') )); then
+      echo "ERROR WHILE RUNNING:" >&2
+      echo "$runref" >&2
+      echo "relative norm error: $rel_error; absolute norm error: $abs_error (rtol=$rtol, atol=$atol)" >&2
+    fi
+    # numdiff $1 $2
   elif [[ "$base" == log_int_* || "$base" == "log_orient_avg" ]]; then
     if [ -n "$RD_TRICKY" ]; then
       return 0
     fi
-    asmin atol 10
+    if [ -n "$SURF_EXT" ]; then
+      asmin atol 10
+      asmin rtol 1
+    else
+      asmin atol 10
+    fi
     numdiff $1 $2
   elif [[ "$base" == "granules" ]]; then # compare only some comments and total number of lines
     if [ `wc -l < $1` == `wc -l < $2` ]; then
@@ -453,7 +493,7 @@ function mycmp {
     numdiff $1 $2
   elif [[ "$base" == DipPol* || "$base" == IntField* ]]; then
     asmin atol 12
-    asmin rtol 6
+    asmin rtol 3
     numdiff $1 $2
   else
     diff $1 $2 >&2
@@ -563,7 +603,7 @@ while read -r cmpfiles cmdline; do
     rm -f -r $SOREF $SOTEST $DIRREF $DIRTEST
     # reference run
     runref="$EXECREF $cmdline -dir $DIRREF"
-    if !($runref <&3 > $SOREF); then
+    if ! ($runref <&3 > $SOREF); then
       if [ -n "$OLDUSED" ]; then  # ignore ADDA errors in older versions
         refok=0
       else
@@ -575,7 +615,7 @@ while read -r cmpfiles cmdline; do
     fi
     # test run
     runtest="$EXECTEST $cmdline -dir $DIRTEST"
-    if !($runtest <&3 > $SOTEST); then
+    if ! ($runtest <&3 > $SOTEST); then
       echo -e "\nERROR while running \n$runtest\nsee $SOTEST" >&2
       exit 1
     fi
@@ -614,7 +654,7 @@ while read -r cmpfiles cmdline; do
         fi
       fi
       if [ "$status" -ne 0 ]; then
-        echo -e "FAILED during '${cmdline}'" >&2
+        echo -e "FAILED during '${runtest}'" >&2
         echo "----------------------------------------" >&2
         status=0
       fi
